### ISSUE TITLE
backoff.Retry with self-instantiated ExponentialBackOff causes panic

### ISSUE THREAD

**Issue by Bo0mer** [cenkalti/backoff#44]
Code:
```
package main

import (
	"errors"
	"fmt"
	"time"

	"github.com/cenkalti/backoff"
)

func main() {
	bo := &backoff.ExponentialBackOff{
		InitialInterval:     500 * time.Millisecond,
		RandomizationFactor: 0.5,
		Multiplier:          1.5,
		MaxInterval:         60 * time.Second,
		MaxElapsedTime:      5 * time.Minute,
		Clock:               backoff.SystemClock,
	}

	op := func() error { return errors.New("kaboom") }
	if err := backoff.Retry(op, bo); err != nil {
		fmt.Println("error", err)
	}
}
```

## What I expect to see
The program should hang until `MaxElapsedTime` passes, and then print an error.

## What I see instead

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x108bb52]

goroutine 1 [running]:
math/rand.(*Rand).Int63(0x0, 0xc420012140)
	/usr/local/go/src/math/rand/rand.go:81 +0x22
math/rand.(*Rand).Float64(0x0, 0x10c0d30)
	/usr/local/go/src/math/rand/rand.go:168 +0x2b
github.com/cenkalti/backoff.(*ExponentialBackOff).NextBackOff(0xc4200160c0, 0x0)
	/Users/ivan/workspace/Go/src/github.com/cenkalti/backoff/exponential.go:121 +0x6f
github.com/cenkalti/backoff.RetryNotify(0x10c0d38, 0x1114340, 0xc4200160c0, 0x0, 0x1133fa8, 0x10a3b80)
	/Users/ivan/workspace/Go/src/github.com/cenkalti/backoff/retry.go:45 +0xe1
github.com/cenkalti/backoff.Retry(0x10c0d38, 0x1114340, 0xc4200160c0, 0x1133fa8, 0x0)
	/Users/ivan/workspace/Go/src/github.com/cenkalti/backoff/retry.go:25 +0x48
main.main()
	/tmp/backoff/main.go:22 +0xe1
exit status 2
```

This is caused by the following line [1]:
```
	return getRandomValueFromInterval(b.RandomizationFactor, b.random.Float64(), b.currentInterval)
```
since `b.random` is nil.

Am I misusing the package? In your test, you set all of `ExponentialBackOff` fields after instantiating the struct with `NewExponentialBackOff` [2], but this seems weird to me.

Adding the following lines to `(*ExponentialBackOff).NextBackOff` should solve the issue (and make the `ExponentialBackOff` type much more usable, IMHO):
```
	if b.random == nil {
		b.random = rand.New(rand.NewSource(time.Now().UnixNano()))
	}
```

I could send a PR if you're ok with the proposed solution.
Thanks,
Ivan

[1] https://github.com/cenkalti/backoff/blob/master/exponential.go#L121
[2] https://github.com/cenkalti/backoff/blob/master/exponential_test.go#L18-L23

**Comment by xoebus** [comment]
We're seeing the same panic with our similar usage.

**Comment by xoebus** [comment]
Thanks!
