### ISSUE TITLE
Timer is nil

### ISSUE THREAD

**Issue by prochac** [cenkalti/backoff#87]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4f3687]

goroutine 1 [running]:
time.(*Timer).Stop(0x0, 0x0)
	/usr/lib/go/src/time/sleep.go:74 +0x27
github.com/cenkalti/backoff/v3.(*defaultTimer).Stop(0xc000258058)
	/home/tom/Workspace/go/pkg/mod/github.com/cenkalti/backoff/v3@v3.2.1/timer.go:32 +0x35
github.com/cenkalti/backoff/v3.RetryNotifyWithTimer.func1(0x11f8740, 0xc000258058)
	/home/tom/Workspace/go/pkg/mod/github.com/cenkalti/backoff/v3@v3.2.1/retry.go:45 +0x33
github.com/cenkalti/backoff/v3.RetryNotifyWithTimer(0xc000256260, 0x11ef5a0, 0xc000098720, 0x0, 0x11f8740, 0xc000258058, 0x0, 0x0)
	/home/tom/Workspace/go/pkg/mod/github.com/cenkalti/backoff/v3@v3.2.1/retry.go:53 +0x42f
github.com/cenkalti/backoff/v3.RetryNotify(0xc000256260, 0x11ef5a0, 0xc000098720, 0x0, 0x0, 0x0)
	/home/tom/Workspace/go/pkg/mod/github.com/cenkalti/backoff/v3@v3.2.1/retry.go:31 +0x5c
github.com/cenkalti/backoff/v3.Retry(0xc000256260, 0x11ef5a0, 0xc000098720, 0x0, 0x0)
	/home/tom/Workspace/go/pkg/mod/github.com/cenkalti/backoff/v3@v3.2.1/retry.go:25 +0x50
github.com/ory/dockertest/v3.(*Pool).Retry(0xc00031e660, 0xc000256260, 0x0, 0x0)
	/home/tom/Workspace/go/pkg/mod/github.com/ory/dockertest/v3@v3.5.2/dockertest.go:405 +0xb0
```

**Comment by cenkalti** [comment]
@prochac Does the issue exist on the latest version? (v4.0.0)

**Comment by ldez** [comment]
we ([lego](https://github.com/go-acme/lego)) encountered the same problem, the use of v4.0.0 solves the problem.

**Comment by prochac** [comment]
> @prochac Does the issue exist on the latest version? (v4.0.0)

> we ([lego](https://github.com/go-acme/lego)) encountered the same problem, the use of v4.0.0 solves the problem.

Based on @ldez comment I gues that no.

I have run into this issue accidentaly by updating all modules without thinking.
github.com/ory/dockertest/v3@v3.5.2 uses github.com/cenkalti/backoff/v3@v3.0.0
